/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSuggestionsRouteImport } from './routes/app.suggestions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPaydayRouteImport } from './routes/app.payday'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppBudgetRouteImport } from './routes/app.budget'
import { Route as AppWishlistIdRouteImport } from './routes/app.wishlist.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuggestionsRoute = AppSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaydayRoute = AppPaydayRouteImport.update({
  id: '/payday',
  path: '/payday',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistIdRoute = AppWishlistIdRouteImport.update({
  id: '/wishlist/$id',
  path: '/wishlist/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/payday': typeof AppPaydayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/': typeof AppIndexRoute
  '/app/wishlist/$id': typeof AppWishlistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/payday': typeof AppPaydayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app': typeof AppIndexRoute
  '/app/wishlist/$id': typeof AppWishlistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/payday': typeof AppPaydayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/': typeof AppIndexRoute
  '/app/wishlist/$id': typeof AppWishlistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/budget'
    | '/app/expenses'
    | '/app/history'
    | '/app/payday'
    | '/app/profile'
    | '/app/suggestions'
    | '/app/'
    | '/app/wishlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/budget'
    | '/app/expenses'
    | '/app/history'
    | '/app/payday'
    | '/app/profile'
    | '/app/suggestions'
    | '/app'
    | '/app/wishlist/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/budget'
    | '/app/expenses'
    | '/app/history'
    | '/app/payday'
    | '/app/profile'
    | '/app/suggestions'
    | '/app/'
    | '/app/wishlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suggestions': {
      id: '/app/suggestions'
      path: '/suggestions'
      fullPath: '/app/suggestions'
      preLoaderRoute: typeof AppSuggestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payday': {
      id: '/app/payday'
      path: '/payday'
      fullPath: '/app/payday'
      preLoaderRoute: typeof AppPaydayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wishlist/$id': {
      id: '/app/wishlist/$id'
      path: '/wishlist/$id'
      fullPath: '/app/wishlist/$id'
      preLoaderRoute: typeof AppWishlistIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppPaydayRoute: typeof AppPaydayRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSuggestionsRoute: typeof AppSuggestionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWishlistIdRoute: typeof AppWishlistIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppPaydayRoute: AppPaydayRoute,
  AppProfileRoute: AppProfileRoute,
  AppSuggestionsRoute: AppSuggestionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppWishlistIdRoute: AppWishlistIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
