// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mturxjoczjjerhddcodm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dXJ4am9jempqZXJoZGRjb2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2ODA5OTcsImV4cCI6MjA5MzI1Njk5N30.DCiobKB673oWDqsn7byy4eq46WLbjR2Evd-XSfD3NcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});